on:
  issues:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Python stuff
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run the script
        run: |
          python -m pip install pygithub
#          python triaging.py -i ${{github.event.issue.number}} -r ${{ github.event.repository.name }} -t ${{ secrets.ISSUE_TRIAGING_PERMS }}
      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: ARMmbed/mbed-os-ci-scripts
          token: ${{ secrets.ISSUE_TRIAGING_PERMS }}
          path: mbed-os-ci-scripts
      - name: Run script from the other repo
        run: |
          cp -a mbed-os-ci-scripts/mbed-os-ci-scripts $(git --exec-path)
          python $(git --exec-path)/mbed-os-ci-scripts/metrics/__init__.py --help
