on:
  issues:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - env: # Set the secret as an input
        GITHUB_TOKEN: ${{ secrets.TestSecret }}

    - uses: actions/checkout@v2
#    - uses: ARMmbed/github-to-jira-test@master
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install pygithub
        python triaging.py -i ${{github.event.issue.number}} -r ${{ github.event.repository.name }}

